### PR TITLE
Bookstore: Use Redux in React components

### PR DESCRIPTION
**Pull request by jicamargo**
# 🎉📚 **Bookstore: Use Redux in React components** 📚🎉

📌 Hey team, I'm excited to share my latest progress on the Bookstore project! 🚀 In this PR, I've implemented Redux in the React components to manage the state of books. Here are the highlights:

✅ Wrapped the `<App>` component with the `<Provider>` component from `react-redux` to enable Redux functionality throughout the app.
✅ Passed the configured store into the `<Provider>` to make it available to all components.
✅ Created an `initialState` variable for the `booksSlice`, which includes the provided book data.
✅ Developed a reusable component to display books fetched from the slice.
✅ Utilized the `useDispatch` hook to dispatch actions within the components.
✅ Added a `<Button>` component with an event handler to add books to the array, including attributes like id, title, and author.
✅ Implemented another `<Button>` component with an event handler to remove books from the array based on their id.

🌟 With these updates, our Bookstore application is now leveraging the power of Redux for efficient state management! 🚀

Please review the changes and let me know your feedback. Feel free to ask any questions or provide suggestions for further improvements.

🎉🙌 Thank you all for your collaboration on this project! 🙌🎉

Best regards,

Jorge camargo

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Submission :red_circle:

invalid-submission

## Hey @jicamargo :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval. Still, we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Mandatory Changes ♻️
- [x] It would be nice if you add the Future Feature section and add some features in that Future Feature section that you are gonna built in the future next 👍
- [x] It would be nice if you have the node_modules_checker in your linters setup to make you not push the node modules in your repo 😊

**Comment by jicamargo** [comment]
hello @HAMMAS-SALEEM ,

Excuse me, i dont understand your requirements about future feature... ? neither the change about node_modules_checker ??? in the prevoius PR I had no problem with this.

I apreciate if you explain me what you mean. Thank you.

**Comment by HAMMAS-SALEEM** [comment]
Hello @jicamargo I hope you are doing well 😊

Sure, I can help you with that. The "Future Feature" section in a readme file is an important part where you list the features that will be added to your project in the future. However, I noticed that your readme file doesn't currently include this section. I recommend adding the "Future Feature" section to your readme to provide clarity on upcoming additions to your project. This will help users and contributors understand what improvements or enhancements they can expect in the future.

Second, the node_modules checker is part of your linter dear so you need to add node_modules_checker in your linter setup according to microverse [linter_setup_for_rails](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml#L37) projects 👍

**Comment by jicamargo** [comment]
Thank you @HAMMAS-SALEEM . With your explanation, I could acomplish your review. it's done and working. 👍🏼

**Review by ShadyShawkat — APPROVED** [review]
## Hi @jicamargo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
